### ISSUE TITLE
Existing tests do not validate parameters, only print them

### ISSUE THREAD

**Issue by mj-heaton** [dcmri/dcmri#129]
## Is your feature request related to a problem? Please describe.
At present, the tests within `test_mods.py` verify that the code runs successfully, but do not actually assert that the paramaters are as expected.

## Describe the solution you'd like
Introduce assertions for the output parameters after the test has run

**Comment by plaresmedima** [comment]
Yes indeed @mj-heaton this is still to do. We paused test development for the models until their API is 100% fixed. At the moment there may still be (minor) tweaks.
