### ISSUE TITLE
Introduce `enum` types

### ISSUE THREAD

**Issue by mj-heaton** [dcmri/dcmri#132]
## Is your feature request related to a problem? Please describe.
At present, the following model options are specified as strings:
- `agent` 'gadoxetate', 'gadobutrol', 'gadopiclenol', 'gadopentetate', 'gadobenate', 'gadodiamide', 'gadoterate', 'gadoteridol' (will produce an error if an invalid agent is specified)
- `sequence` `SS`, `SR` & `lin`. Note: In some cases will not throw if an invalid sequences is passed, e.g., if the user passes "sr" the `Aorta.predict()` method will assume `SS` signal type
- `kinetics` (can have the following values in conc_liver() 'EC', 'IC', 'ICNS', 'ICNSU' and a variety of different values within the model

## Describe the solution you'd like
1. Considering introducing enum classes, such as:

```python
from enum import Enum

class Agent(Enum):
    gadoxetate = "gadoxetate"
    gadobutrol = "gadobutrol"
    gadopiclenol = "gadopiclenol"
    gadopentetate = "gadopentetate"
    gadobenate = "gadobenate"
    gadodiamide = "gadodiamide"
    gadoterate = "gadoterate"
    gadoteridol  = "gadoteridol"

# Then when instantiating a model:

dc.Aorta(agent=Agent.gadobenate)

```
### Note
To maintain backwards compatibility with the existing API, the following code or similar could be used to maintain support for passing strings directly:
```python
import warnings

   if isinstance(agent, str):
        try:
            mode = Agent(mode)
            warnings.warn(
                "Passing a string as the 'agent' argument is deprecated and will be removed in a future version. "
                "Please use the Agent enum instead.",
                DeprecationWarning,
                stacklevel=2
            )
        except ValueError:
            raise ValueError(f"Unsupported agent: {agent}. Valid agents are: {[a.value for a in Agent]}")
```

2. Ensure that invalid model types are handled with an appropriate error

## Test requirements
Update unit tests to exercise invalid agents, sequences & kinetics

**Comment by mj-heaton** [comment]
See also #127

**Comment by plaresmedima** [comment]
@mj-heaton I agree this needs to be improved - especially your second bullet could create hard to track bugs. I am not so sure about the solution with enum classes though is creates additional burden on the user (unless I am misunderstanding).

This is simple and intuitive

```
dc.Aorta(agent='gadobenate')
```

And would need to be replaced by something like this

```
from dcmri import Agent
dc.Aorta(agent=Agent.gadobenate)
```

I would prefer a solution that leaves the burden with the programmer - e.g somewhere define a list with allowed values for a variable like agent, and then inside functions include a check to see if the parameter supplied is in the function - raise an error if not. Would that not work?

```
all_agents = [
    "gadoxetate",
    "gadobutrol",
    "gadopiclenol",
    "gadopentetate",
    "gadobenate",
    "gadodiamide",
    "gadoterate",
    "gadoteridol",
]


def func(agent):
    if agent not in all_agents:
        raise ValueError(agent + ' is not a recognised contrast agent. Possible values are (...)"
```

**Comment by plaresmedima** [comment]
Closing this as we have insert this solution.
