### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'trapezoid'

### ISSUE THREAD

**Issue by FidelNavarro** [dcmri/dcmri#193]
The requirements don't specify a numpy version; however, AortaPortalLiver() model dosen't work as it requires np.trapezoid() made available after numpy 2.0.0

flux_aorta(J_vena, t, dt, E, FFkl, FFk, heartlung, organs, kidneys, liver, tol)
     99 def flux_aorta(J_vena: np.ndarray,
    100                t=None, dt=1.0, E=0.1, FFkl=0.0, FFk=0.5,
    101                heartlung=['pfcomp', (10, 0.2)],
   (...)
    104                liver=['pfcomp', (10, 0.2)],
    105                tol=0.001):
    107     """Whole-body model for indicator flux through the aorta.
    108 
    109     See section :ref:`whole-body-tissues` for a more detailed description of 
   (...)
    179         plt.show()
    180     """
--> 182     dose = np.trapezoid(J_vena, x=t, dx=dt)
    183     min_dose = tol*dose
    185     # Residuals of each pathway

File ~\AppData\Local\anaconda3\Lib\site-packages\numpy\__init__.py:347, in __getattr__(attr)
    344     "Removed in NumPy 1.25.0"
    345     raise RuntimeError("Tester was removed in NumPy 1.25.")
--> 347 raise AttributeError("module {!r} has no attribute "
    348                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'trapezoid'

**Comment by plaresmedima** [comment]
Thanks @FidelNavarro I suspect another dependency has forced your numpy version down to below 2.0.

To avoid issues like this I have replaced numpy.trapezoid by scipy.integrate.trapezoid

Hope that fixes it

#194
